-- Test Script for Cedar Authorization Plugin (Postgres Version)

-- Step 1: Install extension (if not already)
CREATE EXTENSION IF NOT EXISTS pg_authorization;

-- Step 2: Configure (Cluster wide usually, but showing commands)
-- ALTER SYSTEM SET pg_authorization.cedar_agent_url = 'http://localhost:8280';
-- SELECT pg_reload_conf();

-- Step 3: Verify
SELECT * FROM pg_extension WHERE extname = 'pg_authorization';
SELECT pg_authorization_is_enabled();

-- Step 5: Create test schema and tables
CREATE SCHEMA IF NOT EXISTS test_cedar_db;
SET search_path TO test_cedar_db, public;

CREATE TABLE IF NOT EXISTS employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(50),
    salary DECIMAL(10,2),
    hire_date DATE
);

CREATE TABLE IF NOT EXISTS orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    product_name VARCHAR(100),
    quantity INT,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payroll (
    employee_id INT PRIMARY KEY,
    base_salary DECIMAL(10,2),
    bonus DECIMAL(10,2),
    tax_deductions DECIMAL(10,2),
    net_pay DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS public_data (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Step 6: Create test users
DO $$
BEGIN
    -- Create roles if they don't exist
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'alice') THEN CREATE ROLE alice LOGIN PASSWORD 'password123'; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bob') THEN CREATE ROLE bob LOGIN PASSWORD 'password123'; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'charlie') THEN CREATE ROLE charlie LOGIN PASSWORD 'password123'; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'maintenance') THEN CREATE ROLE maintenance LOGIN PASSWORD 'password123'; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'admin_user') THEN CREATE ROLE admin_user LOGIN PASSWORD 'password123'; END IF; -- 'admin' is reserved sometimes or confusing
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hr_user') THEN CREATE ROLE hr_user LOGIN PASSWORD 'password123'; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'developer') THEN CREATE ROLE developer LOGIN PASSWORD 'password123'; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'auditor') THEN CREATE ROLE auditor LOGIN PASSWORD 'password123'; END IF;
END;
$$;

-- Grant usage on schema
GRANT USAGE ON SCHEMA test_cedar_db TO alice, bob, charlie, maintenance, admin_user, hr_user, developer, auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA test_cedar_db TO alice, bob, charlie, maintenance, admin_user, hr_user, developer, auditor;
-- Grant usage on sequences for identity columns
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA test_cedar_db TO alice, bob, charlie, maintenance, admin_user, hr_user, developer, auditor;


-- Step 7: Insert test data
INSERT INTO employees (name, department, salary, hire_date) VALUES
('John Doe', 'Engineering', 75000.00, '2023-01-15'),
('Jane Smith', 'Marketing', 65000.00, '2023-02-20'),
('Bob Johnson', 'Sales', 55000.00, '2023-03-10'),
('Alice Williams', 'HR', 70000.00, '2023-04-05');

INSERT INTO orders (customer_id, product_name, quantity) VALUES
(1, 'Widget A', 10),
(2, 'Widget B', 5),
(3, 'Widget C', 8),
(1, 'Widget D', 12);

INSERT INTO payroll (employee_id, base_salary, bonus, tax_deductions, net_pay) VALUES
(1, 75000.00, 5000.00, 15000.00, 65000.00),
(2, 65000.00, 3000.00, 12000.00, 56000.00),
(3, 55000.00, 2000.00, 10000.00, 47000.00),
(4, 70000.00, 4000.00, 14000.00, 60000.00);

INSERT INTO public_data (title, description) VALUES
('Public Announcement 1', 'This is public information available to all users.'),
('Public Announcement 2', 'Another piece of public information.'),
('Public FAQ', 'Frequently asked questions and answers.');

-- Step 8: Create a test stored procedure (Function in Postgres)
CREATE OR REPLACE FUNCTION calculate_bonus(emp_id INT) RETURNS TEXT AS $$
DECLARE
    bonus_amount DECIMAL(10,2);
BEGIN
    SELECT salary * 0.1 INTO bonus_amount FROM employees WHERE id = emp_id;
    RETURN 'Bonus for employee ' || emp_id || ' is: $' || bonus_amount;
END;
$$ LANGUAGE plpgsql;

-- Step 9: Test queries
-- Note: In psql scripts, we can use \connect or SET SESSION AUTHORIZATION to switch users.

-- Test 1: Alice accessing employees table
SET SESSION AUTHORIZATION alice;
SELECT * FROM employees;
RESET SESSION AUTHORIZATION;

-- Test 2: Bob accessing orders
SET SESSION AUTHORIZATION bob;
SELECT * FROM orders;
INSERT INTO orders (customer_id, product_name, quantity) VALUES (4, 'Test Widget', 1);
RESET SESSION AUTHORIZATION;

-- Test 3: Charlie
SET SESSION AUTHORIZATION charlie;
SELECT * FROM public_data;
RESET SESSION AUTHORIZATION;

-- Test 6: Payroll
SET SESSION AUTHORIZATION alice; -- or appropriate user
SELECT * FROM payroll;
RESET SESSION AUTHORIZATION;

-- Test 7: Delete
SET SESSION AUTHORIZATION alice;
DELETE FROM orders WHERE order_id = 1;
RESET SESSION AUTHORIZATION;

-- Test 9: Procedure execution
SET SESSION AUTHORIZATION developer;
SELECT calculate_bonus(1);
RESET SESSION AUTHORIZATION;

